#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx-role

- name: Ensure nginx package is present
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure nginx service is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create index.html from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Deploy nginx configuration
  template:
    src: default-site.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
